version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
  - package-ecosystem: "npm"
    directory: "/deploy/e3i/v160-rc2"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
