'use strict';
const fs=require('fs');
const PORT=process.env.PORT||'3000',BASE=`http://127.0.0.1:${PORT}`,MODE=process.env.MARKETSPHERE_DURABILITY_CERT_MODE||'recovery',PROOF_PATH=process.env.MARKETSPHERE_DURABILITY_PROOF_PATH,EXPECT_EVENTS=Number(process.env.MARKETSPHERE_DURABILITY_EXPECT_EVENTS||2400);
function die(code,reason,details={}){console.error(JSON.stringify({event:'MARKETSPHERE_V45_DURABILITY_CERT_FAIL',code,reason,...details}));process.exit(code)}
async function get(path){const r=await fetch(BASE+path,{signal:AbortSignal.timeout(5000)});let body;try{body=await r.json()}catch{die(101,'INVALID_JSON',{path,status:r.status})}return{status:r.status,body}}
function equal(a,b,name){if(a!==b)die(102,'PROOF_MISMATCH',{field:name,expected:a,actual:b})}
async function certify(){if(!['seed','recovery'].includes(MODE))die(103,'INVALID_MODE',{mode:MODE});if(!PROOF_PATH)die(104,'PROOF_PATH_REQUIRED');if(process.env.T0_PROMOTION_ENABLED!=='false')die(105,'T0_MUST_REMAIN_DISABLED');if(process.env.CAPITAL_AUTHORITY!=='NONE')die(106,'CAPITAL_AUTHORITY_MUST_BE_NONE');
const health=await get('/api/health'),status=await get('/api/durable/status'),replay=await get('/api/durable/replay'),t0=await get('/api/t0/certification'),order=await get('/api/order');
if(health.status!==200||health.body.ok!==true||health.body.build!=='4.5.0-beta'||health.body.atomic_persistence!==true||health.body.persistence_semantics!=='ATOMIC_FSYNC_RENAME_V1')die(107,'HEALTH_ASSERTION_FAILED',{health});
if(status.status!==200||status.body.atomic_persistence!==true||status.body.persistence_semantics!=='ATOMIC_FSYNC_RENAME_V1'||status.body.capital_authority!=='NONE')die(108,'DURABLE_STATUS_ASSERTION_FAILED',{status});
if(replay.status!==200||replay.body.state!=='DETERMINISTIC'||replay.body.capital_authority!=='NONE')die(109,'REPLAY_ASSERTION_FAILED',{replay});
if(t0.status!==200||t0.body.promotion_enabled!==false||t0.body.state!=='LOCKED_PRE_CREDENTIAL'||t0.body.capital_authority!=='NONE')die(110,'T0_ASSERTION_FAILED',{t0});if(order.status!==403)die(111,'FUNDED_ROUTE_NOT_LOCKED',{status:order.status});
const current={store_instance_id:status.body.store_instance_id,replay_digest:status.body.replay_digest,events:status.body.events,checkpoint_hash:status.body.checkpoint_hash,accepted:status.body.accepted,quarantine:status.body.quarantine,dead:status.body.dead};if(!current.store_instance_id||!current.replay_digest||!current.checkpoint_hash)die(112,'DURABLE_IDENTITY_INCOMPLETE',{current});equal(replay.body.store_instance_id,current.store_instance_id,'replay.store_instance_id');equal(replay.body.digest,current.replay_digest,'replay.digest');equal(replay.body.events,current.events,'replay.events');equal(replay.body.checkpoint_hash,current.checkpoint_hash,'replay.checkpoint_hash');
if(MODE==='seed'){if(status.body.state!=='PROCESS_LOCAL_SANDBOX'||status.body.durable!==false||status.body.backend!=='PROCESS_LOCAL')die(113,'SEED_STORAGE_MODE_INVALID',{status:status.body});if(current.events!==EXPECT_EVENTS)die(114,'SEED_EVENT_COUNT_MISMATCH',{expected:EXPECT_EVENTS,actual:current.events});if(fs.existsSync(PROOF_PATH))die(115,'SEED_PROOF_ALREADY_EXISTS',{proof_path:PROOF_PATH});fs.writeFileSync(PROOF_PATH,JSON.stringify(current,null,2))}else{if(status.body.state!=='DURABLE_VERIFIED'||status.body.durable!==true||status.body.backend!=='FILESYSTEM_VOLUME'||status.body.path_class!=='PERSISTENT_VOLUME')die(116,'RECOVERY_STORAGE_MODE_INVALID',{status:status.body});if(!fs.existsSync(PROOF_PATH))die(117,'RECOVERY_PROOF_MISSING',{proof_path:PROOF_PATH});const prior=JSON.parse(fs.readFileSync(PROOF_PATH,'utf8'));for(const key of ['store_instance_id','replay_digest','events','checkpoint_hash','accepted','quarantine','dead'])equal(prior[key],current[key],key);if(current.events!==EXPECT_EVENTS)die(118,'RECOVERY_EVENT_COUNT_MISMATCH',{expected:EXPECT_EVENTS,actual:current.events})}
console.log(JSON.stringify({event:'MARKETSPHERE_V45_DURABILITY_CERT_PASS',mode:MODE,build:'4.5.0-beta',runtime_sha256:process.env.RUNTIME_SHA256||null,persistence_semantics:'ATOMIC_FSYNC_RENAME_V1',proof_path:PROOF_PATH,...current,t0_promotion_enabled:false,funded_order_routing:false,capital_authority:'NONE'}))}
setTimeout(()=>{certify().catch(error=>die(119,'UNHANDLED_CERT_ERROR',{error:error?.message||String(error)}))},Number(process.env.MARKETSPHERE_DURABILITY_CERT_DELAY_MS||1800));
